# Generated by Django 2.2.1 on 2019-06-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('roll_no', models.CharField(max_length=10)),
                ('phone_no', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
