# Generated by Django 2.2.1 on 2019-06-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='phone_no',
            field=models.CharField(max_length=128),
        ),
    ]
